FROM postgres:15.1
RUN apt-get update && apt install -y postgresql-15-postgis-3 openjdk-17-jdk

COPY /tak-server/tak/ /opt/tak
COPY CoreConfig.xml /opt/tak

ENTRYPOINT ["/opt/tak/db-utils/configureInDocker.sh"]