FROM eclipse-temurin:17-jammy
RUN apt update && \
    apt-get install emacs-nox net-tools netcat vim less -y
ENV COUNTRY_CODE='US'
ENV CITY='Austin'
ENV STATE='Texas'
ENV ORGANIZATION='Austin Voice Data LLC'
ENV ORGANIZATIONAL_UNIT='DevTest'
ENV USER_COUNT=
ENV ADMINS_COUNT=
# ENV ENROLLMENT_TYPE=automated_enrollment
# ENV AUTOMATED_ADMIN_USERNAME=kris-admin
# ENV AUTOMATED_ADMIN_PASSWORD='Q$MHeip!3yFNg8C'
# ENV AUTOMATED_CLIENT_USERNAME=kdtz
# ENV AUTOMATED_CLIENT_PASSWORD='Q$MHeip!3yFNg8C'
# ENV SERVER_NAME=civtakdev
# ENV IP_OR_DOMAIN_NAME=civtakdev.opeongo.net

RUN useradd -g 0 -u 1000 tak \
    && usermod -a -G root tak \
    && mkdir -p /opt/configurator \

RUN mkdir -p /opt/tak \
    && chown tak:0 /opt/tak

# COPY --chown=tak:0 /tak-server/tak/ /opt/tak
COPY --chown=tak:0 configurator.sh /opt/configurator
COPY --chown=tak:0 CoreConfig.xml /opt/configurator
COPY --chown=tak:0 tak-server-configurator-template.pref /opt/configurator
COPY --chown=tak:0 tak-server-configurator-manifest.xml /opt/configurator

# RUN chmod u=rwx /opt/tak \
# 	# && find /opt/tak -type f -name "*.sh" -exec chmod u=rwx {} \; \
# 	&& find /opt/configurator -type f -name "*.sh" -exec chmod u=rwx {} \;
RUN find /opt/configurator -type f -name "*.sh" -exec chmod u=rwx {} \;

USER tak:0

ENTRYPOINT ["/bin/bash", "-c", "/opt/tak/configureInDocker.sh init"]